<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="PSTAT100 Spring 2023">

<title>PSTAT100 - Simple linear regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">PSTAT100</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html">Course syllabus</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../content.html">Materials</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../miscellany.html">Miscellany</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#from-last-time" id="toc-from-last-time" class="nav-link active" data-scroll-target="#from-last-time">From last time</a></li>
  <li><a href="#from-last-time-1" id="toc-from-last-time-1" class="nav-link" data-scroll-target="#from-last-time-1">From last time</a></li>
  <li><a href="#visualizing-the-line" id="toc-visualizing-the-line" class="nav-link" data-scroll-target="#visualizing-the-line">Visualizing the line</a></li>
  <li><a href="#not-a-statistical-model-yet" id="toc-not-a-statistical-model-yet" class="nav-link" data-scroll-target="#not-a-statistical-model-yet">Not a statistical model, yet</a></li>
  <li><a href="#residual-distribution" id="toc-residual-distribution" class="nav-link" data-scroll-target="#residual-distribution">Residual distribution</a></li>
  <li><a href="#residual-distribution-1" id="toc-residual-distribution-1" class="nav-link" data-scroll-target="#residual-distribution-1">Residual distribution</a></li>
  <li><a href="#the-error-model" id="toc-the-error-model" class="nav-link" data-scroll-target="#the-error-model">The error model</a></li>
  <li><a href="#the-simple-linear-regression-model" id="toc-the-simple-linear-regression-model" class="nav-link" data-scroll-target="#the-simple-linear-regression-model">The simple linear regression model</a></li>
  <li><a href="#properties-of-the-normal-distribution" id="toc-properties-of-the-normal-distribution" class="nav-link" data-scroll-target="#properties-of-the-normal-distribution">Properties of the normal distribution</a></li>
  <li><a href="#model-implications" id="toc-model-implications" class="nav-link" data-scroll-target="#model-implications">Model implications</a></li>
  <li><a href="#estimates" id="toc-estimates" class="nav-link" data-scroll-target="#estimates">Estimates</a></li>
  <li><a href="#estimates-matrix-form" id="toc-estimates-matrix-form" class="nav-link" data-scroll-target="#estimates-matrix-form">Estimates (matrix form)</a></li>
  <li><a href="#fitted-values-and-residuals" id="toc-fitted-values-and-residuals" class="nav-link" data-scroll-target="#fitted-values-and-residuals">Fitted values and residuals</a></li>
  <li><a href="#computations" id="toc-computations" class="nav-link" data-scroll-target="#computations">Computations</a></li>
  <li><a href="#parameter-interpretations-intercept" id="toc-parameter-interpretations-intercept" class="nav-link" data-scroll-target="#parameter-interpretations-intercept">Parameter interpretations: intercept</a></li>
  <li><a href="#parameter-interpretations-intercept-1" id="toc-parameter-interpretations-intercept-1" class="nav-link" data-scroll-target="#parameter-interpretations-intercept-1">Parameter interpretations: intercept</a></li>
  <li><a href="#parameter-interpretations-slope" id="toc-parameter-interpretations-slope" class="nav-link" data-scroll-target="#parameter-interpretations-slope">Parameter interpretations: slope</a></li>
  <li><a href="#parameter-interpretations-slope-1" id="toc-parameter-interpretations-slope-1" class="nav-link" data-scroll-target="#parameter-interpretations-slope-1">Parameter interpretations: slope</a></li>
  <li><a href="#parameter-interpretations-error-variance" id="toc-parameter-interpretations-error-variance" class="nav-link" data-scroll-target="#parameter-interpretations-error-variance">Parameter interpretations: error variance</a></li>
  <li><a href="#parameter-interpretations-error-variance-1" id="toc-parameter-interpretations-error-variance-1" class="nav-link" data-scroll-target="#parameter-interpretations-error-variance-1">Parameter interpretations: error variance</a></li>
  <li><a href="#parameter-interpretations-variance" id="toc-parameter-interpretations-variance" class="nav-link" data-scroll-target="#parameter-interpretations-variance">Parameter interpretations: variance</a></li>
  <li><a href="#general-parameter-interpretations" id="toc-general-parameter-interpretations" class="nav-link" data-scroll-target="#general-parameter-interpretations">General parameter interpretations</a></li>
  <li><a href="#centering-the-explanatory-variable" id="toc-centering-the-explanatory-variable" class="nav-link" data-scroll-target="#centering-the-explanatory-variable">Centering the explanatory variable</a></li>
  <li><a href="#other-transformations" id="toc-other-transformations" class="nav-link" data-scroll-target="#other-transformations">Other transformations</a></li>
  <li><a href="#other-transformations-1" id="toc-other-transformations-1" class="nav-link" data-scroll-target="#other-transformations-1">Other transformations</a></li>
  <li><a href="#uncertainty-quantification" id="toc-uncertainty-quantification" class="nav-link" data-scroll-target="#uncertainty-quantification">Uncertainty quantification</a></li>
  <li><a href="#understanding-variation-in-estimates" id="toc-understanding-variation-in-estimates" class="nav-link" data-scroll-target="#understanding-variation-in-estimates">Understanding variation in estimates</a></li>
  <li><a href="#variance-of-least-squares" id="toc-variance-of-least-squares" class="nav-link" data-scroll-target="#variance-of-least-squares">Variance of least squares</a></li>
  <li><a href="#standard-errors" id="toc-standard-errors" class="nav-link" data-scroll-target="#standard-errors">Standard errors</a></li>
  <li><a href="#computations-and-intepretations" id="toc-computations-and-intepretations" class="nav-link" data-scroll-target="#computations-and-intepretations">Computations and intepretations</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence intervals</a></li>
  <li><a href="#visualizing-uncertainty" id="toc-visualizing-uncertainty" class="nav-link" data-scroll-target="#visualizing-uncertainty">Visualizing uncertainty</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simple linear regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>PSTAT100 Spring 2023 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell" data-slideshow="{&quot;slide_type&quot;:&quot;skip&quot;}" data-tags="[]" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> altair <span class="im">as</span> alt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>alt.data_transformers.disable_max_rows()</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># import grade-aggregated seda data from hw2</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>seda <span class="op">=</span> pd.read_csv(<span class="st">'data/seda.csv'</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># filter to math and remove NaNs</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>regdata <span class="op">=</span> seda[seda.subject <span class="op">==</span> <span class="st">'math'</span>].dropna().drop(columns <span class="op">=</span> <span class="st">'subject'</span>).set_index(<span class="st">'id'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="from-last-time" class="level2">
<h2 class="anchored" data-anchor-id="from-last-time">From last time</h2>
<ul>
<li>statistical models are probabilistic represenations of data generating processes
<ul>
<li>some randomness must be present (usually from sampling) for this to be sensible</li>
</ul></li>
<li>regression models relate a variable of interest to one or more other ‘explanatory’ variables and consist of:
<ul>
<li>a distribution for the variable of interest</li>
<li>expression(s) for the distribution’s parameters in terms of the explanatory variable(s)</li>
</ul></li>
<li>for <em>linear</em> regression, the mean of the response is a linear function of the explanatory variable(s)
<ul>
<li>‘simple’ if one explanatory variable</li>
<li>‘multiple’ if many explanatory variables</li>
<li>‘multivariate’ if many variables of interest</li>
</ul></li>
</ul>
</section>
<section id="from-last-time-1" class="level2">
<h2 class="anchored" data-anchor-id="from-last-time-1">From last time</h2>
<p>A simple linear model is <span class="math inline">\(y_i = a x_i + b + e_i\)</span> where <span class="math inline">\(e_i\)</span> are ‘residuals’ – leftover quantities.</p>
<div class="incremental">
<p>The <em>least squares line</em> minimizes the sum of squared residuals <span class="math inline">\(\sum_i e_i^2\)</span> – <em>i.e.,</em> the residual variance, assuming the line passes through the mean.</p>
<p><span class="math display">\[
\begin{align*}
b &amp;= \frac{S_x}{S_y} \text{corr}(x, y) \\
a &amp;= \bar{y} - b\bar{x}
\end{align*}
\]</span></p>
</div>
</section>
<section id="visualizing-the-line" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-line">Visualizing the line</h2>
<p>Verifying that the line plotted on a prediction grid (left) matches the regression transform from Altair (right):</p>
<p><img src="figures/fig4-olsline.png" class="img-fluid"></p>
</section>
<section id="not-a-statistical-model-yet" class="level2">
<h2 class="anchored" data-anchor-id="not-a-statistical-model-yet">Not a statistical model, yet</h2>
<p>The least squares line is simply an algebraic transformation of the data – technically, a projection.</p>
<div class="incremental">
<p>This is not yet a statistical model according to our definition, since there is no probability distribution involved.</p>
</div>
<div class="incremental">
<p>We can change that by considering the residuals to be random.</p>
</div>
</section>
<section id="residual-distribution" class="level2">
<h2 class="anchored" data-anchor-id="residual-distribution">Residual distribution</h2>
<p>Have a look at the histogram of the residuals (with a KDE curve):</p>
<p><img src="figures/fig5a-residhist.png" class="img-fluid"></p>
<div class="incremental">
<p>Does this look like any probability density function you encountered in 120A?</p>
</div>
</section>
<section id="residual-distribution-1" class="level2">
<h2 class="anchored" data-anchor-id="residual-distribution-1">Residual distribution</h2>
<p>The residual distribution is pretty well-approximated by the <em>normal</em> or <em>Gaussian</em> distribution:</p>
<p><img src="figures/fig5b-residnormal.png" class="img-fluid"></p>
</section>
<section id="the-error-model" class="level2">
<h2 class="anchored" data-anchor-id="the-error-model">The error model</h2>
<p>This phenomenon – nearly normal residuals – is pretty common in practice.</p>
<div class="incremental">
<p>So a standard distributional model for the residuals is that they are independent normal random variables. This is written as:</p>
<p><span class="math display">\[
e_i \stackrel{iid}{\sim} N\left(0, \sigma^2\right)
\]</span></p>
</div>
<div class="incremental">
<p>This is an important modification because it induces a probability distribution on <span class="math inline">\(y_i\)</span>.</p>
</div>
</section>
<section id="the-simple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="the-simple-linear-regression-model">The simple linear regression model</h2>
<p>Now we’re in a position to state the <strong>simple linear regression model</strong>:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i \quad
\begin{cases}
i = 1, \dots, n \\
\epsilon_i \sim N\left(0,\sigma^2\right)
\end{cases}
\]</span></p>
<ul>
<li><span class="math inline">\(y_i\)</span> is the <em><strong>response variable</strong></em></li>
<li><span class="math inline">\(x_i\)</span> is the <em><strong>explanatory variable</strong></em></li>
<li><span class="math inline">\(\epsilon_i\)</span> is the <em><strong>random error</strong></em></li>
<li><span class="math inline">\(\beta_0, \beta_1, \sigma^2\)</span> are the <em><strong>model parameters</strong></em>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the <em><strong>intercept</strong></em></li>
<li><span class="math inline">\(\beta_1\)</span> is the <em><strong>coefficient</strong></em></li>
<li><span class="math inline">\(\sigma^2\)</span> is the <em><strong>error variance</strong></em></li>
</ul></li>
</ul>
</section>
<section id="properties-of-the-normal-distribution" class="level2">
<h2 class="anchored" data-anchor-id="properties-of-the-normal-distribution">Properties of the normal distribution</h2>
<p>As a refresher from 120A, if <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span> then:</p>
<ol type="1">
<li>(Mean) <span class="math inline">\(\mathbb{E}X = \mu\)</span></li>
<li>(Variance) <span class="math inline">\(\text{var}X = \sigma^2\)</span></li>
<li>(Linearity) For constants <span class="math inline">\(a, b\)</span>, <span class="math inline">\(aX + b \sim N(a\mu + b, a^2\sigma^2)\)</span></li>
</ol>
</section>
<section id="model-implications" class="level2">
<h2 class="anchored" data-anchor-id="model-implications">Model implications</h2>
<p>Treating the error term as random has a number of implications that follow from the properties of the normal distribution:</p>
<ul>
<li><p>(Normality) The response is a normal random variable: <span class="math inline">\(y_i \sim N\left(\beta_0 + \beta_1 x_i, \sigma^2\right)\)</span></p></li>
<li><p>(Linearity) The mean response is linear in <span class="math inline">\(X\)</span>: <span class="math inline">\(\mathbb{E}y_i = \beta_0 + \beta_1 x_i\)</span></p></li>
<li><p>(Constant variance) The response has variance: <span class="math inline">\(\text{var}y_i = \sigma^2\)</span></p></li>
<li><p>(Independence) The observations are independent (because the errors are): <span class="math inline">\(y_i \perp y_j\)</span></p></li>
</ul>
<div class="incremental">
<p>These are the <strong>assumptions</strong> of the simple linear regression model.</p>
</div>
<div class="incremental">
<p><em>Aside</em>: other error distributions, or conditions that don’t assume a specific distribution, are possible.</p>
</div>
</section>
<section id="estimates" class="level2">
<h2 class="anchored" data-anchor-id="estimates">Estimates</h2>
<p>You’ve already seen how to compute the least squares estimates of <span class="math inline">\(\beta_0, \beta_1\)</span> – these are no different when the errors are random.</p>
<div class="incremental">
<p>Estimates are typically denoted by the corresponding paramater with a hat:</p>
<p><span class="math display">\[
\begin{align*}
\hat{\beta}_1
    &amp;= \frac{
        \sum_i (x_i - \bar{x})(y_i - \bar{y})
        }{
        \sum_i (x_i - \bar{x})^2
        } \\
\hat{\beta}_0
    &amp;= \bar{y} - \hat{\beta}_1 \bar{x}
\end{align*}
\]</span></p>
</div>
<div class="incremental">
<p>An estimate of the error variance is:</p>
<p><span class="math display">\[
\hat{\sigma}^2 = \frac{1}{n - 2} \sum_{i = 1}^n \left(y_i - \hat{\beta}_0 - \hat{\beta}_1 x_i\right)^2
\]</span></p>
</div>
</section>
<section id="estimates-matrix-form" class="level2">
<h2 class="anchored" data-anchor-id="estimates-matrix-form">Estimates (matrix form)</h2>
<p>These estimates can be expressed in matrix form as:</p>
<p><span class="math display">\[
\begin{align*}
\hat{\beta} &amp;= (\mathbf{X'X})^{-1}\mathbf{X'y} \\
\hat{\sigma}^2
    &amp;= \frac{1}{n - 2}\left(\mathbf{y} - \mathbf{X}\hat{\beta}\right)'\left(\mathbf{y} - \mathbf{X}\hat{\beta}\right)
\end{align*}
\]</span></p>
</section>
<section id="fitted-values-and-residuals" class="level2">
<h2 class="anchored" data-anchor-id="fitted-values-and-residuals">Fitted values and residuals</h2>
<p>The projections of the data points onto the line are the estimated values of the response variable for each data point.</p>
<p>These are known as <strong>fitted values</strong> and denoted <span class="math inline">\(\hat{y}_i\)</span>:</p>
<p><span class="math display">\[
\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 x_i
\]</span></p>
<div class="incremental">
<p>Then, the differences between observed and fitted values give the model residuals:</p>
<p><span class="math display">\[
e_i = y_i - \hat{y}_i
\]</span></p>
</div>
</section>
<section id="computations" class="level2">
<h2 class="anchored" data-anchor-id="computations">Computations</h2>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># retrieve data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> sm.tools.add_constant(regdata.log_income.values)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> regdata.gap.values</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># fit regression model</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>slr <span class="op">=</span> sm.OLS(endog <span class="op">=</span> y, exog <span class="op">=</span> x)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># estimates</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> slr.fit().params</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># fitted values</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>fitted <span class="op">=</span> slr.fit().fittedvalues</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># residuals</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>resids <span class="op">=</span> slr.fit().resid</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># error variance estimate</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>sigmasq_hat <span class="op">=</span> slr.fit().scale</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'coefficient estimates: '</span>, beta_hat)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'error variance estimate: '</span>, sigmasq_hat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>coefficient estimates:  [-1.35616996  0.12105696]
error variance estimate:  0.013171170616137325</code></pre>
</div>
</div>
</section>
<section id="parameter-interpretations-intercept" class="level2">
<h2 class="anchored" data-anchor-id="parameter-interpretations-intercept">Parameter interpretations: intercept</h2>
<p>The intercept <span class="math inline">\(\beta_0\)</span> represents the mean response <span class="math inline">\(\mathbb{E}y_i\)</span> when <span class="math inline">\(x_i = 0\)</span>.</p>
<div class="incremental">
<p>In the SEDA example:</p>
<blockquote class="blockquote">
<p>For districts with a log median income of 0, the mean achievement gap between boys and girls is estimated to be -1.356 standard deviations from the national average.</p>
</blockquote>
</div>
<div class="incremental">
<p>Not incorrect, but awkward:</p>
<ul>
<li>log median income is not a natural quantity</li>
<li>the sign is confusing</li>
</ul>
</div>
</section>
<section id="parameter-interpretations-intercept-1" class="level2">
<h2 class="anchored" data-anchor-id="parameter-interpretations-intercept-1">Parameter interpretations: intercept</h2>
<p>Better:</p>
<blockquote class="blockquote">
<p>For school districts with a median income of 1 dollar, the mean achievement gap is estimated to favor girls by 1.356 standard deviations from the national average.</p>
</blockquote>
<ul>
<li>Check your understanding:
<ul>
<li>why 1 dollar and not 0 dollars?</li>
<li>why not -1.356?</li>
</ul></li>
<li>Not of particular interest here because no districts have a median income of 1 USD.</li>
</ul>
</section>
<section id="parameter-interpretations-slope" class="level2">
<h2 class="anchored" data-anchor-id="parameter-interpretations-slope">Parameter interpretations: slope</h2>
<p>The slope <span class="math inline">\(\beta_1\)</span> represents the change in mean response <span class="math inline">\(\mathbb{E}y_i\)</span> per unit change in <span class="math inline">\(x_i\)</span>.</p>
<div class="incremental">
<p>In the SEDA example:</p>
<blockquote class="blockquote">
<p>Each increase of log median income by 1 is associated with an estimated increase in mean achievement gap of 0.121 standard deviations from the national average in favor of boys.</p>
</blockquote>
</div>
<div class="incremental">
<p>Not incorrect, but a bit awkward – how much is a change in log median income of 1 unit?</p>
</div>
</section>
<section id="parameter-interpretations-slope-1" class="level2">
<h2 class="anchored" data-anchor-id="parameter-interpretations-slope-1">Parameter interpretations: slope</h2>
<p>Better:</p>
<blockquote class="blockquote">
<p>Every doubling of median income is associated with an estimated increase in the mean achievement gap of 0.084 standard deviations from the national average in favor of boys.</p>
</blockquote>
<ul>
<li>Why doubling??</li>
<li><em>Hint:</em> <span class="math inline">\(\hat{\beta}_1\log (2x) = \hat{\beta}_1\log x + \hat{\beta}_1 \log 2\)</span></li>
</ul>
</section>
<section id="parameter-interpretations-error-variance" class="level2">
<h2 class="anchored" data-anchor-id="parameter-interpretations-error-variance">Parameter interpretations: error variance</h2>
<p>The error variance <span class="math inline">\(\sigma^2\)</span> represents the variability in the response <span class="math inline">\(y\)</span> after accounting for the explanatory variable <span class="math inline">\(x\)</span>.</p>
<div class="incremental">
<p>In the SEDA example:</p>
<blockquote class="blockquote">
<p>After adjusting for log median income, the gender achievement gap varies among districts by an estimated 0.11 standard deviations from the national average.</p>
</blockquote>
</div>
<div class="incremental">
<p><em>Note</em> that <span class="math inline">\(\hat{\sigma}\)</span> is reported for interpretation on the original scale, rather than <span class="math inline">\(\hat{\sigma}^2\)</span>.</p>
</div>
</section>
<section id="parameter-interpretations-error-variance-1" class="level2">
<h2 class="anchored" data-anchor-id="parameter-interpretations-error-variance-1">Parameter interpretations: error variance</h2>
<p>Compare the estimated ‘raw’ variance in gender gap with the estimated residual variance after accounting for log median income:</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'raw variance: '</span>, y.var(ddof <span class="op">=</span> <span class="dv">1</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'estimated residual variance: '</span>, sigmasq_hat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>raw variance:  0.015355417268162816
estimated residual variance:  0.013171170616137325</code></pre>
</div>
</div>
<div class="incremental">
<p>The estimated variability in achievement gap diminishes a little after adjusting for log median income. The relative reduction is:</p>
<p><span class="math display">\[
\frac{\hat{\sigma}^2_\text{raw} - \hat{\sigma}^2}{\hat{\sigma}^2_\text{raw}}
\]</span></p>
</div>
<div class="incremental">
<p>In the SEDA example, the reduction was about 14%:</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'relative reduction in variance: '</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    (y.var(ddof <span class="op">=</span> <span class="dv">1</span>) <span class="op">-</span> sigmasq_hat)<span class="op">/</span>y.var(ddof <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>relative reduction in variance:  0.14224599787035444</code></pre>
</div>
</div>
</div>
</section>
<section id="parameter-interpretations-variance" class="level2">
<h2 class="anchored" data-anchor-id="parameter-interpretations-variance">Parameter interpretations: variance</h2>
<p>A closely related quantity is the <em>R-squared statistic</em>, which simply adjusts the denominator of the error variance estimate:</p>
<p><span class="math display">\[
\frac{\hat{\sigma}^2_\text{raw} - \frac{n - 2}{n - 1}\hat{\sigma}^2}{\hat{\sigma}^2_\text{raw}}
\]</span></p>
<ul>
<li>used as a measure of fit</li>
<li>interpreted as the proportion of variation in the response explained by the model</li>
</ul>
</section>
<section id="general-parameter-interpretations" class="level2">
<h2 class="anchored" data-anchor-id="general-parameter-interpretations">General parameter interpretations</h2>
<p>There is some general language for interpreting the parameter estimates:</p>
<ul>
<li><p>(Intercept) When [<span class="math inline">\(x_i = 0\)</span>] the mean [response variable] is estimated to be [<span class="math inline">\(\hat{\beta}_0\)</span> units].</p></li>
<li><p>(Slope) Every [one-unit increase in <span class="math inline">\(x_i\)</span>] is associated with an estimated change in mean [response variable] of [<span class="math inline">\(\hat{\beta}_1\)</span> units].</p></li>
<li><p>(Error variance) After adjusting for [explanatory variable], the remaining variability in [response variable] is an estimated [<span class="math inline">\(\hat{\sigma}\)</span> units] about the mean.</p></li>
</ul>
<div class="incremental">
<p>You can use this standard language as a formulaic template for interpreting estimated parameters.</p>
</div>
</section>
<section id="centering-the-explanatory-variable" class="level2">
<h2 class="anchored" data-anchor-id="centering-the-explanatory-variable">Centering the explanatory variable</h2>
<p>If we want the intercept to be meaningful, we could center the explanatory variable and instead fit:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 (x_i - \bar{x}) + \epsilon_i
\]</span></p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># center log median income</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>log_income_ctr <span class="op">=</span> (regdata.log_income <span class="op">-</span> regdata.log_income.mean()).values</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># form x matrix</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>x_ctr <span class="op">=</span> sm.tools.add_constant(log_income_ctr)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># refit model</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>slr_ctr <span class="op">=</span> sm.OLS(endog <span class="op">=</span> y, exog <span class="op">=</span> x_ctr)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>beta_hat_ctr <span class="op">=</span> slr_ctr.fit().params</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># display parameter estimates</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'coefficient estimates: '</span>, beta_hat_ctr)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'error variance estimate: '</span>, slr_ctr.fit().scale)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>coefficient estimates:  [-0.02105724  0.12105696]
error variance estimate:  0.013171170616137325</code></pre>
</div>
</div>
<div class="incremental">
<blockquote class="blockquote">
<p>For a district with average log median income, the estimated achievement gap favors boys by 0.021 standard deviations from the national average.</p>
</blockquote>
<ul>
<li>note that this is just a location shift so other estimates are unchanged</li>
<li>can recover the original intercept estimate as <span class="math inline">\(\hat{\beta}_0 - \hat{\beta}_1 \bar{x}\)</span></li>
</ul>
</div>
<div class="incremental">
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>beta_hat_ctr[<span class="dv">0</span>] <span class="op">-</span> beta_hat_ctr[<span class="dv">1</span>]<span class="op">*</span>regdata.log_income.mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>-1.3561699570330032</code></pre>
</div>
</div>
</div>
</section>
<section id="other-transformations" class="level2">
<h2 class="anchored" data-anchor-id="other-transformations">Other transformations</h2>
<p>We could seek to adjust the model so that the intercept is interpreted as the gap at the district with the smallest median income:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 \log\left(x_i - x_{(1)} + 1 \right), \quad x_i: \text{median income for district } i
\]</span></p>
<div class="incremental">
<p>But this changes the meaning of the other model terms:</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> represents the change in mean gap associated with multiplicative changes in the amount by which a district’s median income exceeds that of the poorest district</li>
<li><span class="math inline">\(\sigma^2\)</span> is the variability of the gap after adjusting for the log of the difference in median income from the median income of the poorest district</li>
</ul>
</div>
</section>
<section id="other-transformations-1" class="level2">
<h2 class="anchored" data-anchor-id="other-transformations-1">Other transformations</h2>
<p>Unsurprisingly, estimates are not invariant under arbitrary transformations, so if the meanings of the other parameters change, then so do the estimates:</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># center log median income</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>income <span class="op">=</span> np.exp(regdata.log_income) </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>income_shifted <span class="op">=</span> income <span class="op">-</span> income.<span class="bu">min</span>()</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>log_income_shifted <span class="op">=</span> np.log(income_shifted <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># form x matrix</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>x_shifted <span class="op">=</span> sm.tools.add_constant(log_income_shifted)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># refit model</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>slr_shifted <span class="op">=</span> sm.OLS(endog <span class="op">=</span> y, exog <span class="op">=</span> x_shifted)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>beta_hat_shifted <span class="op">=</span> slr_shifted.fit().params</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co"># display parameter estimates</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'coefficient estimates: '</span>, beta_hat_shifted)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'error variance estimate: '</span>, slr_shifted.fit().scale)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>coefficient estimates:  const        -0.544166
log_income    0.049851
dtype: float64
error variance estimate:  0.013904979364206385</code></pre>
</div>
</div>
<div class="incremental">
<p>Note also it’s not possible to express the old parameters as functions of the new parameters; this is a fundamentally different model.</p>
</div>
</section>
<section id="uncertainty-quantification" class="level2">
<h2 class="anchored" data-anchor-id="uncertainty-quantification">Uncertainty quantification</h2>
<p>A great benefit of the simple linear regression model relative to a best-fit line is that the error variance estimate allows for <em>uncertainty quantification</em>.</p>
<div class="incremental">
<p>What that means is that one can describe precisely:</p>
<ul>
<li><p>variation in the estimates (<em>i.e.</em>, estimated model reliability);</p></li>
<li><p>variation in predictions made using the estimated model (<em>i.e.</em>, predictive reliability).</p></li>
</ul>
</div>
</section>
<section id="understanding-variation-in-estimates" class="level2">
<h2 class="anchored" data-anchor-id="understanding-variation-in-estimates">Understanding variation in estimates</h2>
<p>What would happen to the estimates if they were computed from a different sample?</p>
<div class="incremental">
<p>We can explore this idea a little by calculating least squares estimates from several distinct <em>subsamples</em> of the dataset.</p>
<p><img src="figures/fig6-subsamples.png" class="img-fluid"></p>
</div>
<div class="incremental">
<p>The lines are pretty similar, but they change a bit from subsample to subsample.</p>
</div>
</section>
<section id="variance-of-least-squares" class="level2">
<h2 class="anchored" data-anchor-id="variance-of-least-squares">Variance of least squares</h2>
<blockquote class="blockquote">
<p><em>How much should one expect the estimates to change depending on the data they are fit to?</em></p>
</blockquote>
<div class="incremental">
<p>It can be shown that the variances and covariance of the estimates are:</p>
<p><span class="math display">\[
\left[\begin{array}{cc}
    \text{var}\hat{\beta}_0 &amp; \text{cov}\left(\hat{\beta}_0, \hat{\beta}_1\right) \\
    \text{cov}\left(\hat{\beta}_0, \hat{\beta}_1\right) &amp;\text{var}\hat{\beta}_1
    \end{array}\right]
   = \sigma^2 \left(\mathbf{X'X}\right)^{-1}
\]</span></p>
</div>
<div class="incremental">
<p>Bear in mind that the randomness comes from the <span class="math inline">\(\epsilon_i\)</span> model term.</p>
<ul>
<li>these quantify how much the parameters vary across collections of <span class="math inline">\(y_i\)</span>’s measured <em>at exactly the same values of <span class="math inline">\(x_i\)</span></em></li>
<li>these are <strong>not</strong> variances of the parameters; <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are constants, <em>i.e.</em>, not random</li>
<li>they are also <strong>not</strong> variances of the estimates – <em>e.g.,</em> <span class="math inline">\(0.121\)</span> is yet another constant</li>
</ul>
</div>
</section>
<section id="standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="standard-errors">Standard errors</h2>
<p>So the variances can be <em>estimated</em> by plugging in <span class="math inline">\(\color{red}{\hat{\sigma}^2}\)</span> for <span class="math inline">\(\sigma\)</span> in the variance-covariance matrix from the previous slide.</p>
<div class="incremental">
<p>The estimated standard deviations are known as <em>standard errors</em>:</p>
<p><span class="math display">\[
\text{SE}(\hat{\beta}_0) = \sqrt{\color{red}{\hat{\sigma}^2}(\mathbf{X'X})^{-1}_{11}} \qquad\text{and}\qquad \text{SE}(\hat{\beta}_1) = \sqrt{\color{red}{\hat{\sigma}^2}(\mathbf{X'X})^{-1}_{22}}
\]</span></p>
</div>
</section>
<section id="computations-and-intepretations" class="level2">
<h2 class="anchored" data-anchor-id="computations-and-intepretations">Computations and intepretations</h2>
<p>The estimated variance-covariance of the least squares estimates is computed by the <code>.cov_params()</code> method:</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>slr.fit().cov_params()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>array([[ 0.01708179, -0.00154692],
       [-0.00154692,  0.00014026]])</code></pre>
</div>
</div>
<ul>
<li>the intercept estimate varies by an estimated <span class="math inline">\(\sqrt{0.0171} = 0.131\)</span> across datasets, with <span class="math inline">\(x_i\)</span> fixed</li>
<li>the slope estimate varies by an estimated <span class="math inline">\(\sqrt{0.00014} = 0.0118\)</span> across datasets, with <span class="math inline">\(x_i\)</span> fixed</li>
</ul>
</section>
<section id="confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals">Confidence intervals</h2>
<p>About 95% of the time, the true values <span class="math inline">\(\beta_0, \beta_1\)</span> will be within 2SE of any particular estimates <span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1\)</span>.</p>
<div class="incremental">
<p>The intervals <span class="math inline">\(\hat{\beta}_j \pm 2 SE(\hat{\beta}_j)\)</span> provide <em>ranges</em> of possible values for the true values <span class="math inline">\(\beta_j\)</span>:</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>slr.fit().conf_int()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>array([[-1.61283063, -1.09950928],
       [ 0.09779946,  0.14431446]])</code></pre>
</div>
</div>
</div>
<div class="incremental">
<p>This supports two important inferences:</p>
<ul>
<li>with 95% confidence, the intercept is estimated to be between -1.613 and -1.010</li>
<li>with 95% confidence, the slope is estimated to be between 0.098 and 0.144</li>
</ul>
</div>
<div class="incremental">
<p>And the width of those intervals conveys a sense of the uncertainty associated with the estimates.</p>
</div>
</section>
<section id="visualizing-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-uncertainty">Visualizing uncertainty</h2>
<p>It’s fairly common practice to add a <em>band</em> around the plotted line to indicate estimated variability.</p>
<div class="columns">
<div class="column" style="width:65%;">
<p><img src="figures/fig7-uncertaintyband.png" class="img-fluid"></p>
</div><div class="column" style="width:35%;">
<ul>
<li>represents the uncertainty/variability of the parameter estimates, <em>i.e.,</em> of the <em>trend line</em></li>
<li>does <strong>not</strong> represent the uncertainty/variability of the observations – note the spread of data is considerably broader than the uncertainty band</li>
</ul>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>