---
title: "Materials"
format: html
---

## Useful links

- [Attendance form](https://forms.gle/y4CW7QPM4KSKexrq9) (fill out once per class meeting, including sections)
- [Gradescope](https://www.gradescope.com/courses/527056) (for assignment submissions)
- [LSIT server](https://pstat100.lsit.ucsb.edu) (for course computing)

## Getting started checklist

- Confirm access to all course pages
- Read syllabus
- Fill out [intake survey](https://forms.gle/Vb3XU5pCwcs6ieVw8)

## Week 1

*Readings*: 

- LDS1 [The Data Science Lifecycle](https://learningds.org/ch/01/lifecycle_intro.html) 
- LDS5 [Case Study: Why is my Bus Always Late?](https://learningds.org/ch/05/bus_intro.html)
- PDSH2.1 [Understanding data types in python](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)
- PDSH2.2 [The basics of numpy arrays](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html)
- PDSH2.4 [Aggregations: min, max, and everything in between](https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html)

**Monday**: Course introduction [[slides](slides/week1-intro.qmd)]

**Lab sections**: Orientation to Jupyter notebooks [[html](labs/lab0-gettingstarted/lab0-gettingstarted.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Flab0-gettingstarted%2Flab0-gettingstarted.ipynb&branch=main)] [[solutions](labs/lab0-gettingstarted/lab0-gettingstarted-soln.ipynb)]

**Wednesday**: Data science lifecycle [[slides](slides/week1-lifecycle.qmd)]

## Week 2

*Readings*:

- Wickham (2014). Tidy data. *Journal of statistical software* 59(10). [[link to paper](https://www.jstatsoft.org/article/view/v059i10)]
- PDSH3.1 [Introducing pandas objects](https://jakevdp.github.io/PythonDataScienceHandbook/03.01-introducing-pandas-objects.html)
- PDSH3.2 [Data indexing and selection](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html)
- PDSH3.7 [Merge and join](https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html)
- PDSH3.8 [Aggregation and grouping](https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html)

*Assignments*: 

* HW1, BRFSS case study, due Monday, April 24 [[html](hw/hw1-brfss/hw1-brfss.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Fhw1-brfss%2Fhw1-brfss.ipynb&branch=main)] [[solutions](hw/hw1-brfss/hw1-brfss-soln.ipynb)]

**Monday**: Tidy data [[slides](slides/week2-tidy.qmd)]

**Lab sections**: Pandas [[html](labs/lab1-pandas/lab1-pandas.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Flab1-pandas%2Flab1-pandas.ipynb&branch=main)] [[solutions](labs/lab1-pandas/lab1-pandas-soln.ipynb)]

**Wednesday**: Dataframe transformations [[slides](slides/week2-transform.qmd)]

## Week 3

*Readings*:

- LDS2.2 [Population, frame, sample](https://learningds.org/ch/02/data_scope_construct.html#)
- Van Buuren, Flexible Imputation of Missing Data, section 2.2 [Concepts in incomplete data](https://stefvanbuuren.name/fimd/sec-idconcepts.html)
- PDSH3.4 [Handling missing data](https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html)


*Assignments*:

- Mini project 1, due Monday, May 1 [[html](projects/mp1/mp1-airquality.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Fmp1-airquality%2Fmp1-airquality.ipynb&branch=main)] 

**Monday**: Sampling, bias, and missingness [[slides](slides/week3-sampling.qmd)]

**Lab sections**: Exploring sampling bias through simulation [[html](labs/lab2-sampling/lab2-sampling.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Flab2-sampling%2Flab2-sampling.ipynb&branch=main)] [[solutions](labs/lab2-sampling/lab2-sampling-soln.ipynb)]

**Wednesday**: Voter fraud case study [[slides](slides/week3-casestudy.qmd)] [[activity html](activities/week3-activity-miller.ipynb)] [[activity notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Factivities%2Fweek3-activity-miller.ipynb&branch=main)]

## Week 4

*Readings*:

- Wilke, [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) Ch. 2-5 
- LDS11.1 [Choosing scale to reveal structure](https://learningds.org/ch/11/viz_scale.html)
- (Recommended) Cook, D., Lee, E. K., & Majumder, M. (2016). Data visualization and statistical graphics in big data analysis. Annual Review of Statistics and Its Application, 3, 133-159. [[link to paper](https://www.annualreviews.org/doi/full/10.1146/annurev-statistics-041715-033420)]
- (Recommended) Gelman, A., & Unwin, A. (2013). Infovis and statistical graphics: different goals, different looks. Journal of Computational and Graphical Statistics, 22(1), 2-28. [[link to paper](https://www.tandfonline.com/doi/full/10.1080/10618600.2012.761137)]
- (Recommended) Iliinsky, N. (2010). On beauty. Beautiful visualization: Looking at data through the eyes of experts, 1-13. [[link to chapter](http://mines.humanoriented.com/568/reading/bv_ch01.pdf)]

*Assignments*: 

- HW2, SEDA case study, due Monday, May 8 [[html](hw/hw2-seda/hw2-seda.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Fhw2-seda%2Fhw2-seda.ipynb&branch=main)] [[solutions](hw/hw2-seda/hw2-seda-soln.ipynb)]

**Monday**: Statistical graphics [[slides](slides/week4-graphics.qmd)]

**Lab sections**: Data visualization [[html](labs/lab3-visualization/lab3-visualization.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Flab3-visualization%2Flab3-visualization.ipynb&branch=main)] [[solutions](labs/lab3-visualization/lab3-visualization-soln.ipynb)]

**Wednesday**: Principles of figure design [[slides](slides/week4-principles.qmd)]

## Week 5

*Readings*:

- LDS 11.2 [Smoothing and aggregating data](https://learningds.org/ch/11/viz_smoothing.html)
- Scott, D.W. (2012). Multivariate Density Estimation and Visualization. In: Gentle, J., Härdle, W., Mori, Y. (eds) Handbook of Computational Statistics. [[link to chapter](https://doi.org/10.1007/978-3-642-21551-3_19)]

**Monday**: Exploratory analysis and density estimation [[slides](slides/week5-density.qmd)]

**Lab sections**: Smoothing [[html](labs/lab4-smoothing/lab4-smoothing.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Flab4-smoothing%2Flab4-smoothing.ipynb&branch=main)] [[solutions](labs/lab4-smoothing/lab4-smoothing-soln.ipynb)]

**Wednesday**: Multivariate KDE, mixture models, and scatterplot smoothing [[slides](slides/week5-smoothing.qmd)] [[activity html](activities/week5-activity-smoothing.ipynb)] [[activity notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Factivities%2Fweek5-activity-smoothing.ipynb&branch=main)]

## Week 6

*Readings*:

- LDS 10.2-10.5 [Exploratory data analysis](https://learningds.org/ch/10/eda_distributions.html) 
- PDSH5.9 [Principal component andalysis](https://jakevdp.github.io/PythonDataScienceHandbook/05.09-principal-component-analysis.html)

*Assignments*:

- HW3, Diatom paleoclimatology case study, due Monday, May 22 [[html](hw/hw3-diatom/hw3-diatom.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Fhw3-diatom%2Fhw3-diatom.ipynb&branch=main)]

**Monday**: Covariance, correlation, and spectral decomposition [[slides](slides/week6-covariation.qmd)]

_**NO lab sections this week**_

**Wednesday**: Principal components [[slides](slides/week6-pca.qmd)]

## Week 7

*Readings*:

- LDS 15.1-15.3 [Simple linear models](https://learningds.org/ch/15/linear_intro.html)

*Assignments*:

- Mini project 2, due Tuesday, May 30 [[html](projects/mp2/mp2-ncca.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Fmp2-ncca%2Fmp2-ncca.ipynb&branch=main)]

**Monday**: Modeling concepts; least squares [[slides](slides/week7-lse.qmd)]

**Lab sections**: Principal components [[html](labs/lab5-pca/lab5-pca.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Flab5-pca%2Flab5-pca.ipynb&branch=main)]

**Wednesday**: The simple linear regression model [[slides](slides/week7-slr.qmd)]

## Week 8

*Readings*:

- LDS 17.5 [Basics of prediction intervals](https://learningds.org/ch/17/inf_pred_gen_PI.html)
- LDS 15.4 [Multiple regression](https://learningds.org/ch/15/linear_multi.html)

*Assignments*: 

- HW4, Discrimination in disability benefit allocation, due Monday, June 5

**Monday**: Prediction [[slides](slides/week8-prediction.qmd)]

**Lab sections** Fitting regression models [[html](labs/lab6-regression/lab6-regression.ipynb)] [[notebook](https://pstat100.lsit.ucsb.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fruizt%2Fpstat100-content&urlpath=lab%2Ftree%2Fpstat100-content%2Flab6-regression%2Flab6-regression.ipynb&branch=main)]